package main.domain;

import static main.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class EventiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventiAllPropertiesEquals(Eventi expected, Eventi actual) {
        assertEventiAutoGeneratedPropertiesEquals(expected, actual);
        assertEventiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventiAllUpdatablePropertiesEquals(Eventi expected, Eventi actual) {
        assertEventiUpdatableFieldsEquals(expected, actual);
        assertEventiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventiAutoGeneratedPropertiesEquals(Eventi expected, Eventi actual) {
        assertThat(actual)
            .as("Verify Eventi auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventiUpdatableFieldsEquals(Eventi expected, Eventi actual) {
        assertThat(actual)
            .as("Verify Eventi relevant properties")
            .satisfies(a -> assertThat(a.getTitolo()).as("check titolo").isEqualTo(expected.getTitolo()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a ->
                assertThat(a.getPrezzo()).as("check prezzo").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrezzo())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventiUpdatableRelationshipsEquals(Eventi expected, Eventi actual) {
        assertThat(actual)
            .as("Verify Eventi relationships")
            .satisfies(a -> assertThat(a.getPrenotazione()).as("check prenotazione").isEqualTo(expected.getPrenotazione()));
    }
}
