package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrenotazioniAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrenotazioniAllPropertiesEquals(Prenotazioni expected, Prenotazioni actual) {
        assertPrenotazioniAutoGeneratedPropertiesEquals(expected, actual);
        assertPrenotazioniAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrenotazioniAllUpdatablePropertiesEquals(Prenotazioni expected, Prenotazioni actual) {
        assertPrenotazioniUpdatableFieldsEquals(expected, actual);
        assertPrenotazioniUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrenotazioniAutoGeneratedPropertiesEquals(Prenotazioni expected, Prenotazioni actual) {
        assertThat(actual)
            .as("Verify Prenotazioni auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrenotazioniUpdatableFieldsEquals(Prenotazioni expected, Prenotazioni actual) {
        assertThat(actual)
            .as("Verify Prenotazioni relevant properties")
            .satisfies(a -> assertThat(a.getData()).as("check data").isEqualTo(expected.getData()))
            .satisfies(a -> assertThat(a.getOraInizio()).as("check oraInizio").isEqualTo(expected.getOraInizio()))
            .satisfies(a -> assertThat(a.getOraFine()).as("check oraFine").isEqualTo(expected.getOraFine()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrenotazioniUpdatableRelationshipsEquals(Prenotazioni expected, Prenotazioni actual) {
        assertThat(actual)
            .as("Verify Prenotazioni relationships")
            .satisfies(a -> assertThat(a.getStato()).as("check stato").isEqualTo(expected.getStato()))
            .satisfies(a -> assertThat(a.getUtente()).as("check utente").isEqualTo(expected.getUtente()))
            .satisfies(a -> assertThat(a.getSala()).as("check sala").isEqualTo(expected.getSala()));
    }
}
