package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatiPrenotazioneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatiPrenotazioneAllPropertiesEquals(StatiPrenotazione expected, StatiPrenotazione actual) {
        assertStatiPrenotazioneAutoGeneratedPropertiesEquals(expected, actual);
        assertStatiPrenotazioneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatiPrenotazioneAllUpdatablePropertiesEquals(StatiPrenotazione expected, StatiPrenotazione actual) {
        assertStatiPrenotazioneUpdatableFieldsEquals(expected, actual);
        assertStatiPrenotazioneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatiPrenotazioneAutoGeneratedPropertiesEquals(StatiPrenotazione expected, StatiPrenotazione actual) {
        assertThat(actual)
            .as("Verify StatiPrenotazione auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatiPrenotazioneUpdatableFieldsEquals(StatiPrenotazione expected, StatiPrenotazione actual) {
        assertThat(actual)
            .as("Verify StatiPrenotazione relevant properties")
            .satisfies(a -> assertThat(a.getDescrizione()).as("check descrizione").isEqualTo(expected.getDescrizione()))
            .satisfies(a -> assertThat(a.getCodice()).as("check codice").isEqualTo(expected.getCodice()))
            .satisfies(a -> assertThat(a.getOrdineAzione()).as("check ordineAzione").isEqualTo(expected.getOrdineAzione()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatiPrenotazioneUpdatableRelationshipsEquals(StatiPrenotazione expected, StatiPrenotazione actual) {
        // empty method
    }
}
