package main.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UtentiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtentiAllPropertiesEquals(Utenti expected, Utenti actual) {
        assertUtentiAutoGeneratedPropertiesEquals(expected, actual);
        assertUtentiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtentiAllUpdatablePropertiesEquals(Utenti expected, Utenti actual) {
        assertUtentiUpdatableFieldsEquals(expected, actual);
        assertUtentiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtentiAutoGeneratedPropertiesEquals(Utenti expected, Utenti actual) {
        assertThat(actual)
            .as("Verify Utenti auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtentiUpdatableFieldsEquals(Utenti expected, Utenti actual) {
        assertThat(actual)
            .as("Verify Utenti relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getNomeAzienda()).as("check nomeAzienda").isEqualTo(expected.getNomeAzienda()))
            .satisfies(a -> assertThat(a.getNumeroDiTelefono()).as("check numeroDiTelefono").isEqualTo(expected.getNumeroDiTelefono()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtentiUpdatableRelationshipsEquals(Utenti expected, Utenti actual) {
        // empty method
    }
}
